### ISSUE TITLE
Helpers getting removed when server restarts

### ISSUE THREAD

**Issue by Akuroma** [jasonwynn10/MyPlot#120] opened 2017-12-23 21:13 UTC
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue Description
Recently added helpers getting removed, when the server stops and restarts. I'm using MySQL to store data of MyPlot.

## Reproducing the issue
1. configure MySQL settings for MyPlot
2. add a Helper to a plot#
3. restart the server

## Client information
PocketMine-MP Version: PocketMine-MP 1.7dev-522 「[REDACTED]」3.0.0-ALPHA10 for 1.2.7 / 1.2.8
Plugin Version: 1.1.7
PHP version: 7.0.13 (default)

**Comment by jasonwynn10** [comment] 2018-01-15 01:51
How soon is the shutting down occurring from when the helpers were added?

**Comment by Akuroma** [comment] 2018-01-15 14:19
That doesn't matter. My players adding helpers all the time. As the server restarts, all helpers getting removed.

**Comment by jasonwynn10** [comment] 2018-01-15 14:33
Only when the server restarts?

**Comment by Aericio** [comment] 2018-09-10 08:56
Issue could not be reproduced, and the issue is too old. It may have been fixed in the newer versions.

**Closed** 2018-09-10 08:57 UTC
Labels: Resolution: Obsolete, Status: Unconfirmed
