### ISSUE TITLE
Custom road designs for MyPlot

### ISSUE THREAD

**Issue by GamerDaniel3000** [jasonwynn10/MyPlot#212] opened 2019-03-03 09:00 UTC
Hey Jason I would like custom roads like in PlotSquard.
That you can then configure the streets as they like one the most.

Thank you for your attention!

Example: https://m.imgur.com/a/GPp0sW6

**Comment by jasonwynn10** [comment] 2020-01-03 00:00
duplicate of #205

**Closed by jasonwynn10** 2020-01-03 00:00 UTC
Labels: Category: Feature Request, Priority: Low, Status: TODO
