### ISSUE TITLE
Water on the Road and Plot Border

### ISSUE THREAD

**Issue by DragonfireHD** [jasonwynn10/MyPlot#341] opened 2020-10-02 12:42 UTC
Issue description

Expected result: The plots have a wall where example water or lava can't flow over it even without the edge

Actual result: Water was placed on the edge of a plot and this now flows on the street!!!
Steps to reproduce the problem
1st place water without a border inside the plotting water odee lava
2. Plot owners can place water on plot edges even with slaps or blocks

OS and versions
Plugin Version: build version MyPlot_dev-615 1.7.0
PocketMine-MP: 3.15.1
PHP: 7.3.21
*Game version: PE and Windows
So befor you delete the message please look this and please fix this problem but the plot rand border higher please and please wee need liquid water and lava border for roads

![Screenshot_20200929_181556_com mojang minecraftpe](https://user-images.githubusercontent.com/50929188/94924026-143ffd00-04bd-11eb-8e9c-4e8091809365.jpg)

**Comment by jasonwynn10** [comment] 2020-10-02 12:53
duplicate of #339

**Closed by jasonwynn10** 2020-10-02 12:53 UTC
