### ISSUE TITLE
All the help pages display the same information

### ISSUE THREAD

**Issue by NML32** [jasonwynn10/MyPlot#21] opened 2016-11-03 21:37 UTC
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
All the help pages display the same commands.

## Reproducing the issue
type /p help, /p help 1, /p help 2, etc

## Client information
Operating system Linux, PHP version: 7.0.9, Server Genisys-unsupported-b6cec51 (0.16)

## Optional information
N/A

**Comment by jasonwynn10** [comment] 2016-11-10 01:58
if there are no more reports of this issue, I am going to mark this as wontfix

**Comment by isoz** [comment] 2016-11-21 01:47
I can confirm, couldn't you just load the plugin yourself and test it?

**Comment by jasonwynn10** [comment] 2016-11-21 02:32
Sorry, but I can't. I only have a network at my school with limited access, so I can't run a server there or at my house.

**Comment by isoz** [comment] 2016-11-21 02:33
That's kind of scary, you make changes without testing it and then we load it into our live servers thinking it's safe and then everything falls apart. 

When you picked this project, by this project I mean, I consider this to be one of the most complete plugins in the whole pocketmine community, you assumed a responsibility.

Well, ill help however I can...

**Comment by jasonwynn10** [comment] 2016-11-21 02:35
Please do

**Comment by Aericio** [comment] 2016-11-21 02:48
Oh... deny and undeny makes more lag?

**Comment by isoz** [comment] 2016-11-21 02:48
That's not what I said, I said the plugin in general is more laggy could be related to the popup tasks since they're kinda slow to load, than the old one.

**Comment by Aericio** [comment] 2016-11-21 02:49
@jasonwynn10 Do you need a 0.16.2 apk file?

**Comment by jasonwynn10** [comment] 2016-11-21 02:58
I don't have a device anymore. My iPod 5 was broken and I haven't been able to get anything to replace it yet

**Comment by jasonwynn10** [comment] 2016-11-21 03:01
anyway, this is the wrong place to talk about this

**Comment by Aericio** [comment] 2016-12-09 05:04
![image](https://cloud.githubusercontent.com/assets/16523741/21038357/1251710c-bd79-11e6-97cf-89d24ac3d707.png)

**Comment by jasonwynn10** [comment] 2016-12-09 20:43
Okay, I have a question. Do you want multiple pages or one page with everything?

**Comment by Aericio** [comment] 2016-12-10 07:47
Multiple pages would be better, one page with everything is annoying. If people keep chatting, it'll bump up the lines and you won't be able to see some commands. Also for stupidity reasons.

**Comment by jasonwynn10** [comment] 2016-12-10 16:59
Please test the most recent version

**Comment by jasonwynn10** [comment] 2017-01-25 00:58
this should fix the help pages theororetically... 2b3069c

**Closed** 2017-01-28 19:48 UTC
Labels: Category: Bug, Priority: Low, Resolution: Fixed, Status: Confirmed
