### ISSUE TITLE
Bugs v2

### ISSUE THREAD

**Issue by Aericio** [jasonwynn10/MyPlot#11] opened 2016-10-03 04:19 UTC
## TODO

- [x] /p denyplayer + /p undenyplayer not working (unknown commands)
- [x] Unknown Cause
  `Notice: Array to string conversion in src\MyPlot\provider\SQLiteDataProvider.php on line 84`
- [ ] Update all other language packs
- [x] Test on all available server cores
  - [x] Clearsky
  - [x] Genisys
  - [x] pmmp/PocketMine
  - [x] PocketMine-MP
  - [x] if your running imagicalmine, shoo.

**Comment by Aericio** [comment] 2016-10-03 05:37
If the crashes are fixed, I can start using this on an online server.

**Comment by jasonwynn10** [comment] 2016-10-03 11:17
there aren't any commands besides generate for the console

**Comment by jasonwynn10** [comment] 2016-10-03 21:06
The plugin needs retested

**Comment by Aericio** [comment] 2016-10-07 08:08
I will have time on Sunday to test. Will be updating this shortly!

**Comment by Aericio** [comment] 2016-10-09 04:45
Well, I have some time today. I'll test all the commands.

**Comment by Ad5001** [comment] 2016-10-09 10:41
Had the same problem for my custom private version of MyPlots. You will need to add all translations.

**Comment by Aericio** [comment] 2016-10-13 07:27
Heh, forgot about this. I will *actually* test tomorrow.

**Comment by jasonwynn10** [comment] 2016-10-17 17:31
did the test run well? @Aericio

**Comment by jasonwynn10** [comment] 2016-10-17 17:31
what needs done?

**Comment by Aericio** [comment] 2016-10-18 04:37
![image](https://cloud.githubusercontent.com/assets/16523741/19464529/c04f9d1a-9498-11e6-81a1-3c91b465d069.png)
I generated a new plot world... either its my system or MyPlot really just pooped itself.

**Comment by jasonwynn10** [comment] 2016-10-18 11:08
nope. have you used the generate command? are you on the right world?

**Comment by jasonwynn10** [comment] 2016-10-18 11:08
it could be broken for windows 10 mcpe

**Comment by Aericio** [comment] 2016-10-19 03:04
> I generated a new plot world...

I don't think its Windows 10 MCPE, how does that change anything?

**Comment by Aericio** [comment] 2016-10-19 07:50
@SalmonGER Can you try testing?

**Comment by SalmonGER** [comment] 2016-10-19 07:58
@Aericio /p generate Test worked fine for me. I had a new world named Test with Plots.

**Comment by Aericio** [comment] 2016-10-19 08:03
Now, WOULD YOU LIKE TO TEST THE PLUGIN?

**Comment by jasonwynn10** [comment] 2016-10-19 10:34
@SalmonGER are there any commands not working?

**Comment by TDMidkwhatisxd** [comment] 2016-10-31 09:03
I see that /p return unknown command on 0.16 + i added /p command in plugins.yml and it return nothing!

This fix is for 0.16?

**Comment by Aericio** [comment] 2016-10-31 09:33
We didn't test this for 0.16.0 yet... but MyPlot should still be working in 0.16.0. Are you sure you have it installed?

**Comment by TDMidkwhatisxd** [comment] 2016-10-31 09:34
I fix it myself, test on 0.16, your version wont work!!

**Comment by Aericio** [comment] 2016-10-31 09:40
As I said, we never tested it on 0.16.0 and we never updated it since 0.16.0 came out.

**Comment by TDMidkwhatisxd** [comment] 2016-10-31 10:31
Ok! Non Op players have no acces to /p command!

**Comment by jasonwynn10** [comment] 2016-10-31 11:13
the individual /p command can be used by any player, however the subcommands have a permission limitation

**Comment by TDMidkwhatisxd** [comment] 2016-10-31 14:59
Please test it before talking -_-' ! And dont use op account !
/p = unknown command ;)

**Comment by RocoWayne** [comment] 2016-10-31 15:01
im having the same problem @TDMidkwhatisxd ! All my non OP users cant use /p auto , /p claim, anything. And the group have the perms, in v15 it works just fine.

**Comment by jasonwynn10** [comment] 2016-10-31 15:03
Please make a new issue for that then because this issue thread is for the 0.15 bugs yet to be worked out.

**Comment by Aericio** [comment] 2016-11-01 02:25
Only data flags etc have changed, 2.0.0 API still works with 0.16.0

**Comment by jasonwynn10** [comment] 2016-11-02 00:08
can someone test the deny and undeny commands?

**Comment by jasonwynn10** [comment] 2016-11-02 11:16
@TDMidkwhatisxd @Aericio can either of you test the plugin? I need a test in genesis, pocketmine, and clearsky.

**Comment by TDMidkwhatisxd** [comment] 2016-11-02 11:39
I can easly do that, but if u still need me, im free tomorow, i got my hands full with moving to another vps!

**Comment by jasonwynn10** [comment] 2016-11-02 12:22
Thanks. I think all the bugs are now patched, so I'm going to be releasing the 1.1.0 major patch for MyPlots soon

**Comment by TDMidkwhatisxd** [comment] 2016-11-02 13:59
Ok! Tomorow i will start testing on, Clearsky, Genisys, PmmP

**Comment by jasonwynn10** [comment] 2016-11-02 14:46
I already tested on pmmp and pocketmine

**Comment by TDMidkwhatisxd** [comment] 2016-11-03 05:48
I think i was scammed by eterhost.net ;-; ! From yesterday i wait reply and/or activate my vps!
Sorry, im really bussy, dam these rip off hosters!

**Comment by Aericio** [comment] 2016-11-03 08:20
Just run the server on your home computer and join it via localhost.

**Comment by TDMidkwhatisxd** [comment] 2016-11-03 08:21
The thing is , im bussy searching for a new host to run my servers on!

**Comment by jasonwynn10** [comment] 2016-11-03 11:06
you can host it from your home and use mcpe.me to give it a web address from your home IP

**Comment by TDMidkwhatisxd** [comment] 2016-11-03 12:20
My internet not so great! Btw i finished now i will test

**Comment by TDMidkwhatisxd** [comment] 2016-11-03 12:37
Error: "Call to a member function hasPermission() on null" (EXCEPTION) in "/plugins/Mytest.phar/src/MyPlot/subcommand/DenyPlayerSubCommand" at line 30
I got this error wen used /p deny.

I did /p deny SteveXXL

**Comment by TDMidkwhatisxd** [comment] 2016-11-03 12:48
Latest ClearSky
ClearSky Crash Dump Thu Nov 3 07:46:12 CDT 2016

Error: Uncaught Error: Call to a member function hasPermission() on null in phar:///storage/emulated/legacy/Genisys/plugins/Mytest.phar/src/MyPlot/subcommand/DenyPlayerSubCommand.php:30
File: /Mytest.phar/src/MyPlot/subcommand/DenyPlayerSubCommand
Line: 30
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: MyPlot v1.1.0

Code:
[21]         $plot = $this->getPlugin()->getPlotByPosition($sender->getPosition());
[22]         if ($plot === null) {
[23]             $sender->sendMessage(TextFormat::RED . $this->translateString("notinplot"));
[24]             return true;
[25]         }
[26]         if ($plot->owner !== $sender->getName() and !$sender->hasPermission("myplot.admin.denyplayer")) {
[27]             $sender->sendMessage(TextFormat::RED . $this->translateString("notowner"));
[28]             return true;
[29]         }
[30]         if($this->getPlugin()->getServer()->getPlayer($dplayer)->hasPermission("myplot.admin.bypassdeny")) {
[31]             $sender->sendMessage($this->translateString("denyplayer.cannotdeny", [$dplayer]));
[32]             $dp->sendMessage($this->translateString("denyplayer.attempteddeny", [$sender->getName()]));
[33]             return true;
[34]         }
[35]         if (!$plot->denyPlayer($dplayer)) {
[36]             $sender->sendMessage($this->translateString("denyplayer.alreadydenied", [$dplayer]));
[37]             return true;
[38]         }
[39]         if ($this->getPlugin()->savePlot($plot)) {
[40]             $sender->sendMessage($this->translateString("denyplayer.success1", [$dplayer]));

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ClearSky version: 1.1 #500 [Protocol 91; API 2.1.0]
uname -a: Linux localhost 3.4.67 #1 SMP PREEMPT Tue Dec 16 20:29:49 CST 2014 armv7l
PHP Version: 7.0.3
Zend version: 3.0.0

**Comment by jasonwynn10** [comment] 2016-11-03 12:48
I see, ima fix it real fast

**Comment by Aericio** [comment] 2016-11-04 03:44
@TDMidkwhatisxd Use pmmp's 0.16.0 branch so its more accurate (since they have more 0.16.0 fixes)

**Comment by Aericio** [comment] 2016-11-04 03:45
Make sure your using the '0.16.0' branches of the servercores.

**Comment by TDMidkwhatisxd** [comment] 2016-11-04 04:20
As always

**Comment by jasonwynn10** [comment] 2016-11-10 02:02
All that needs done now is the language pack updates...

**Closed by jasonwynn10** 2016-11-10 02:02 UTC
Labels: bug, help wanted
