### ISSUE TITLE
Plot Merche and custom rand

### ISSUE THREAD

**Issue by note3crafter** [jasonwynn10/MyPlot#224] opened 2019-06-23 10:11 UTC
Can you add custom rand and merch [2 small plots to one big plot]?

**Comment by Wertzui123** [comment] 2019-06-23 13:07
It's called "merging". And no, it isn't easy you think...
/p border is curently avable by a plugin script.

**Comment by note3crafter** [comment] 2019-06-23 13:16
I know that it is not easy, but you could start to introduce something because somebody has to start

**Comment by Wertzui123** [comment] 2019-06-23 14:59
You're right. Please start with plot merging (:

**Comment by note3crafter** [comment] 2019-06-23 15:42
this plugin is for me to big oof

**Comment by jasonwynn10** [comment] 2019-06-29 15:39
duplicate of #59

**Closed by jasonwynn10** 2019-06-29 15:39 UTC
Labels: Category: Feature Request, Resolution: Did not follow Issue Template, Resolution: Duplicate, Resolution: Invalid
