### ISSUE TITLE
[BUG]: (Protection Bug) Can't build on road of a merged plot

### ISSUE THREAD

**Issue by supercrafter333** [jasonwynn10/MyPlot#424] opened 2021-08-15 10:11 UTC
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Merge some plots
2. Try to build on the road as non-op player

### OS and versions

* Plugin Version: 1.11.1
* PocketMine-MP: 3.22.1
* PHP: 7.4
* Game version: PE/Win 10

**Comment by jasonwynn10** [comment] 2021-08-15 12:00
duplicate of #399

**Closed** 2021-08-15 12:01 UTC
