### ISSUE TITLE
Plot Auto Delete Question!

### ISSUE THREAD

**Issue by MonoAdrian23** [jasonwynn10/MyPlot#295] opened 2020-05-20 11:18 UTC
Hey Jason, would it be possible to reset plots automatically after a certain amount of time?
Example: Player has not been online for 2 months.
The plot is automatically reset.
Thank you!

**Comment by jasonwynn10** [comment] 2020-05-20 11:28
duplicate of #9

**Closed by jasonwynn10** 2020-05-20 11:28 UTC
