### ISSUE TITLE
Different sized plots.

### ISSUE THREAD

**Issue by ZandercraftGames** [jasonwynn10/MyPlot#192] opened 2018-09-14 21:09 UTC
Just wondering when you will be putting plot merging or allow worlds with different-sized plots.

**Comment by jasonwynn10** [comment] 2018-09-14 21:12
I've gone over the reason plot merging is going to take a while in my discord server a few times. There are too many complications with the database system and AxisAlignedBoundingBoxes at the moment to make an easy implementation. As for worlds with different-sized plots, does that mean something different from plot merging? If so, could you specify?

Duplicate of #59

**Comment by ZandercraftGames** [comment] 2018-09-14 21:17
Where I could have one world with 16x16 plots and one with 128x128 plots

**Comment by jasonwynn10** [comment] 2018-09-14 21:19
That feature is already implemented. Adjust your config.yml settings before creating a new world and it will use the new settings in world generation

**Closed by jasonwynn10** 2018-09-14 21:19 UTC
Labels: Resolution: Duplicate

**Comment by ZandercraftGames** [comment] 2018-09-14 21:26
hmm so... the plugin wont recognize 4 plots as one?

**Comment by jasonwynn10** [comment] 2018-09-14 21:31
In the plugin's current state, it will not.
