### ISSUE TITLE
sqlite3 required

### ISSUE THREAD

**Issue by ZandercraftGames** [jasonwynn10/MyPlot#177] opened 2018-07-25 20:07 UTC
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?
I just dragged the latest .phar file into the folder and started the server and I get an error that says:
[15:01:08] [Server thread/ERROR]: Required extension sqlite3 not loaded
[15:01:08] [Server thread/CRITICAL]: Could not load plugin 'MyPlot'

## Reproducing the issue
1. Drag .phar into plugins folder.
2. Start server.

## Client information
PocketMine-MP Version: PocketMine-MP 3.1.1 for Minecraft: PE v.1.5.0 (protocol version 274) 
Plugin Version: Dev #219 (&b570)
PHP version: 7.2.1 (default)

## Optional information
```
[15:07:22] [Server thread/ERROR]: Required extension sqlite3 not loaded
[15:07:22] [Server thread/CRITICAL]: Could not load plugin 'MyPlot'
```

**Comment by jasonwynn10** [comment] 2018-07-26 00:01
Duplicate of #168

**Closed by jasonwynn10** 2018-07-26 00:01 UTC
Labels: Resolution: Server Software Issue
