### ISSUE TITLE
The server crashed, how should it be solved

### ISSUE THREAD

**Issue by 673818565** [jasonwynn10/MyPlot#157] opened 2018-05-30 14:41 UTC
[09:34:09] [Server thread/INFO]: Loading source plugin MyPlot v1.2.5

Fatal error: Class 'pocketmine\level\generator\biome\Biome' not found in /root/trs/plugins/MyPlot-API3/src/MyPlot/Commands.php on line 59
[09:34:10] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

The server crashed, how should it be solved

**Comment by jasonwynn10** [comment] 2018-05-31 00:28
Duplicate of #152

**Closed by jasonwynn10** 2018-05-31 00:28 UTC
Labels: API 3, Category: Bug, Category: Duplicate, Resolution: Invalid Bleeding Edge Build, Status: TODO
